version: '3.7'

services:
  # Spring Boot backend
  backend:
    build:
      context: ./lbg-car-react-starter-main  # Path to your Spring Boot project
    container_name: springboot-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  # React frontend
  frontend:
    build:
      context: ./lbg-car-spring-app-starter-main  # Path to your React project
    container_name: react-frontend
    ports:
      - "8000:8000"

  # MySQL database
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql-data:
    driver: local
